
import type { Bylaw } from '@/lib/types';

// This is a temporary in-memory store for the prototype.
// A proper database should be used in a production application.
export const initialRecords: Bylaw[] = [
  {
    id: 'rec-1',
    municipality: 'Leeds and 1000 Islands',
    region: 'Leeds and Grenville',
    contactName: 'Amanda Werner-Mackeler',
    contactMethod: 'planningtechnician@townshipleeds.on.ca',
    conservationAuthority: 'CRCA',
    areaRegulation: 'Yes',
    perimeterRegulation: 'Yes',
    widthRegulation: '20 percent or 15 m',
    lengthRegulation: 'Width of frontage',
    sideLotSetback: '4.6 m',
    lotLineProjection: '4.6 m',
    heightLimit: '6 m',
    permitRequirements: 'Yes boathouse',
    status: 'Verified',
    lastVerified: '2026-03-17',
    notes: 'Current spreadsheet entry is concise. Add source bylaw section and link before production use.',
  },
  {
    id: 'rec-2',
    municipality: 'Athens',
    region: 'Leeds and Grenville',
    contactName: 'Michelle Hollingsworth',
    contactMethod: 'athensmh@myhighspeed.ca',
    conservationAuthority: 'CRCA',
    areaRegulation: 'N A',
    perimeterRegulation: 'N A',
    widthRegulation: '20 percent or 15 m',
    lengthRegulation: 'N A',
    sideLotSetback: '4.5 m',
    lotLineProjection: 'N A',
    heightLimit: '5 m',
    permitRequirements: 'Yes boathouse',
    status: 'Verified',
    lastVerified: '2026-03-17',
    notes: 'Good candidate for a simple rule card.',
  },
  {
    id: 'rec-3',
    municipality: 'Augusta',
    region: 'Leeds and Grenville',
    contactName: 'Melissa Banford',
    contactMethod: 'mbanford@augusta.ca',
    conservationAuthority: 'CRCA',
    areaRegulation: 'N A',
    perimeterRegulation: 'N A',
    widthRegulation: 'N A',
    lengthRegulation: 'N A',
    sideLotSetback: '3.0 m',
    lotLineProjection: 'No encroachment stated',
    heightLimit: '5.0 to 6.5 m',
    permitRequirements: 'Yes boathouse and dock',
    status: 'Needs source link',
    lastVerified: '2026-03-17',
    notes: 'Height rule should likely be split into min max or condition based fields.',
  },
];
